export { default as HeroSection } from "./hero-section"
export { default as Services } from "./services"
export { default as Projects } from "./projects"
export { default as About } from "./about"
export { default as ContactForm } from "./contact-form"
export { default as Footer } from "./footer"
